In [39]:
from torch.utils.data import DataLoader

from torchvision.datasets import MNIST
from torchvision.transforms import Compose, Normalize, ToTensor

In [61]:
data_dir = "../Data"

# I used torch.std_mean to find the values given to Normalize
mnist_xforms = Compose([ToTensor(), Normalize((0.1307,), (0.3081,))])

# Load data files
train_data = MNIST(root=data_dir, train=True, download=True, transform=mnist_xforms)
valid_data = MNIST(root=data_dir, train=False, download=True, transform=mnist_xforms)

In [67]:
# Data loaders provide an easy interface for interactive with data
train_loader = DataLoader(train_data, batch_size=len(train_data))
valid_loader = DataLoader(valid_data, batch_size=len(valid_data))

In [69]:
# This odd bit of code forces the train loader to give us all inputs and targets
X_train, y_train = next(iter(train_loader))
X_valid, y_valid = next(iter(valid_loader))

In [71]:
print("Training input shape    :", X_train.shape)
print("Training target shape   :", y_train.shape)
print("Validation input shape  :", X_valid.shape)
print("Validation target shape :", y_valid.shape)

Training input shape    : torch.Size([60000, 1, 28, 28])
Training target shape   : torch.Size([60000])
Validation input shape  : torch.Size([10000, 1, 28, 28])
Validation target shape : torch.Size([10000])


In [2]:
import torch
a = torch.randn(100)
b = torch.randn(100, 784)
c = a @ b
c.shape

torch.Size([784])

In [4]:
a = torch.randn(5, 1)
a

tensor([[ 0.6586],
        [ 0.5106],
        [-0.5494],
        [-0.2956],
        [-0.5093]])

In [8]:
b = torch.ones(1, 5)
b

tensor([[1., 1., 1., 1., 1.]])

In [10]:
b.T @ a.T

tensor([[ 0.6586,  0.5106, -0.5494, -0.2956, -0.5093],
        [ 0.6586,  0.5106, -0.5494, -0.2956, -0.5093],
        [ 0.6586,  0.5106, -0.5494, -0.2956, -0.5093],
        [ 0.6586,  0.5106, -0.5494, -0.2956, -0.5093],
        [ 0.6586,  0.5106, -0.5494, -0.2956, -0.5093]])

In [13]:
N, nl = 10, 4
b = torch.randn(nl, 1)
ONE = torch.ones(N, 1)
print(ONE @ b.T)

tensor([[-0.3605,  0.0425,  0.9150, -0.3210],
        [-0.3605,  0.0425,  0.9150, -0.3210],
        [-0.3605,  0.0425,  0.9150, -0.3210],
        [-0.3605,  0.0425,  0.9150, -0.3210],
        [-0.3605,  0.0425,  0.9150, -0.3210],
        [-0.3605,  0.0425,  0.9150, -0.3210],
        [-0.3605,  0.0425,  0.9150, -0.3210],
        [-0.3605,  0.0425,  0.9150, -0.3210],
        [-0.3605,  0.0425,  0.9150, -0.3210],
        [-0.3605,  0.0425,  0.9150, -0.3210]])
